name: Deploy .NET App to Render from deploy branch

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Sync main to deploy branch
        run: |
          git checkout -B deploy
          git push origin deploy --force

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x' 

      - name: Build .NET project
        run: |
          dotnet restore
          dotnet build --configuration Release
          dotnet test --no-build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t myapp:latest .

      - name: Test Docker container
        run: |
          docker run --rm myapp:latest echo "Container works!"
